default['storm']['version'] = '0.9.5'
default['storm']['nimbus'] = 'node207'
default['storm']['ui'] = 'node207'
default['storm']['worker']['1'] = 'node206'
default['storm']['worker']['2'] = 'node207'
default['storm']['worker']['3'] = 'node208'

default['storm']['supervisor']['nimbus']['1'] = '[program:storm-nimbus]'
default['storm']['supervisor']['nimbus']['2'] = 'command=/usr/local/storm/bin/storm nimbus'
default['storm']['supervisor']['nimbus']['3'] = 'user=storm'
default['storm']['supervisor']['nimbus']['4'] = 'autostart=true'
default['storm']['supervisor']['nimbus']['5'] = 'autorestart=true'
default['storm']['supervisor']['nimbus']['6'] = 'startsecs=10'
default['storm']['supervisor']['nimbus']['7'] = 'startretries=999'
default['storm']['supervisor']['nimbus']['8'] = 'log_stdout=true'
default['storm']['supervisor']['nimbus']['9'] = 'log_stderr=true'
default['storm']['supervisor']['nimbus']['10'] = 'logfile=/var/log/storm/nimbus.out'
default['storm']['supervisor']['nimbus']['11'] = 'logfile_maxbytes=20MB'
default['storm']['supervisor']['nimbus']['12'] = 'logfile_backups=10'

default['storm']['supervisor']['ui']['1'] = '[program:storm-ui]'
default['storm']['supervisor']['ui']['2'] = 'command=/usr/local/storm/bin/storm ui'
default['storm']['supervisor']['ui']['3'] = 'user=storm'
default['storm']['supervisor']['ui']['4'] = 'autostart=true'
default['storm']['supervisor']['ui']['5'] = 'autorestart=true'
default['storm']['supervisor']['ui']['6'] = 'startsecs=10'
default['storm']['supervisor']['ui']['7'] = 'startretries=999'
default['storm']['supervisor']['ui']['8'] = 'log_stdout=true'
default['storm']['supervisor']['ui']['9'] = 'log_stderr=true'
default['storm']['supervisor']['ui']['10'] = 'logfile=/var/log/storm/ui.out'
default['storm']['supervisor']['ui']['11'] = 'logfile_maxbytes=20MB'
default['storm']['supervisor']['ui']['12'] = 'logfile_backups=10'

default['storm']['supervisor']['slave']['1'] = '[program:storm-supervisor]'
default['storm']['supervisor']['slave']['2'] = 'command=/usr/local/storm/bin/storm supervisor'
default['storm']['supervisor']['slave']['3'] = 'user=storm'
default['storm']['supervisor']['slave']['4'] = 'autostart=true'
default['storm']['supervisor']['slave']['5'] = 'autorestart=true'
default['storm']['supervisor']['slave']['6'] = 'startsecs=10'
default['storm']['supervisor']['slave']['7'] = 'startretries=999'
default['storm']['supervisor']['slave']['8'] = 'log_stdout=true'
default['storm']['supervisor']['slave']['9'] = 'log_stderr=true'
default['storm']['supervisor']['slave']['10'] = 'logfile=/var/log/storm/supervisor.out'
default['storm']['supervisor']['slave']['11'] = 'logfile_maxbytes=20MB'
default['storm']['supervisor']['slave']['12'] = 'logfile_backups=10'
