# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# TestImage	ami-662c2634
Vagrant.configure(2) do |config|
	#config.vm.box = "dummy"
	
	config.omnibus.chef_version = :latest
	#config.berkshelf.berksfile_path = "./Berksfile"
	#config.berkshelf.enabled = true

	config.vm.define 'node203' do |node|
		node.vm.box = "dummy"
		node.omnibus.chef_version = :latest
		node.berkshelf.berksfile_path = "./Berksfile"
		node.berkshelf.enabled = true
		node.vm.synced_folder ".", "/vagrant", disabled: true

		node.vm.provider :aws do |aws, override|
		aws.access_key_id = "AKIAIGU7DLSLT6IAXS6A"
		aws.secret_access_key = "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"
		aws.keypair_name = "aws"
		aws.instance_type = "t1.micro"
		aws.ami = "ami-e6a1abb4" #Java8.1
		aws.region = "ap-southeast-1"
		aws.private_ip_address = "10.0.0.203"
		aws.subnet_id = "subnet-c741f0b0"
		aws.elastic_ip = true
		aws.security_groups = ["sg-6dbadc08"]
		override.ssh.username = "root"
		override.ssh.private_key_path = "/Users/mikechak/Downloads/aws.pem"
		aws.tags = {
			'Name' => 'Node203'
		}
		#aws.block_device_mapping = [
		#{:DeviceName => "/dev/sda", :VirtualName => "ebs", 'Ebs.DeleteOnTermination' => true }
		#]
		end
	
		node.vm.provision :chef_solo do |chef|
		chef.add_recipe "base::master"
		chef.add_recipe "base::namenode"
		end
	end

	config.vm.define 'node204' do |node|
		node.vm.box = "dummy"
		node.omnibus.chef_version = :latest
		node.berkshelf.berksfile_path = "./Berksfile"
                node.berkshelf.enabled = true
		node.vm.synced_folder ".", "/vagrant", disabled: true

		node.vm.provider :aws do |aws, override|
        	aws.access_key_id = "AKIAIGU7DLSLT6IAXS6A"
        	aws.secret_access_key = "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"
        	aws.keypair_name = "aws"
        	aws.instance_type = "t1.micro"
		aws.ami = "ami-e6a1abb4" #Java8.1
        	aws.region = "ap-southeast-1"
        	aws.private_ip_address = "10.0.0.204"
        	aws.subnet_id = "subnet-c741f0b0"
        	aws.elastic_ip = true
        	aws.security_groups = ["sg-6dbadc08"]
        	override.ssh.username = "root"
        	override.ssh.private_key_path = "/Users/mikechak/Downloads/aws.pem"
		aws.tags = {
                        'Name' => 'Node204'
                }
		end

        	node.vm.provision :chef_solo do |chef|
		chef.add_recipe "base::slave"
                chef.add_recipe "base::zookeeper"
                chef.add_recipe "base::datanode"
                chef.add_recipe "base::secondarynamenode"
                chef.add_recipe "base::mapreduce"
                chef.add_recipe "base::resourcemanager"
                chef.add_recipe "base::nodemanager"
                chef.add_recipe "base::jobhistory"
                chef.add_recipe "base::proxyserver"
    		end
	end
end
