# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# TestImage	ami-662c2634
Vagrant.configure(2) do |config|
	config.vm.box = "dummy"	
	config.omnibus.chef_version = :latest
	config.berkshelf.berksfile_path = "./Berksfile"
	config.berkshelf.enabled = true

	config.vm.provider :aws do |aws, override|
		aws.access_key_id = "AKIAIGU7DLSLT6IAXS6A"
                aws.secret_access_key = "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"
                aws.keypair_name = "aws"
                aws.instance_type = "t1.micro"
                aws.ami = "ami-662c2634"
                aws.region = "ap-southeast-1"
                aws.private_ip_address = "10.0.0.10"
                aws.subnet_id = "subnet-c741f0b0"
                #aws.elastic_ip = true
                aws.security_groups = ["sg-6dbadc08"]
                override.ssh.username = "root"
                override.ssh.private_key_path = "/Users/mikechak/Downloads/aws.pem"
	end

	config.vm.provision :chef_solo do |chef|
                chef.add_recipe "base::default"
        end
end
